import { NextResponse } from "next/server";

// ✅ Allowed email list
const ALLOWED_EMAILS = new Set([
  "adaweepa@gmail.com",
  "wktsdealwis28@gmail.com",
  "mwrlakmali@gmail.com",
  "chinthakanirmal07@gmail.com",
  "fouzmeezaahsan@gmail.com",
  "hetti_77@yahoo.com",
  "amalidilrukshi1985@gmail.com",
  "chamiramadushan1980@gmail.com",
  "mal.d2004@gmail.com",
  "anushikam877@gmail.com",
  "rcw2007@gmail.com",
  "tharindipbi@gmail.com",
  "themirades@gmail.com",
  "charithccr@gmail.com",
  "yamunaabesirinarayanage@gmail.com",
  "kalanapriyar@gmail.com",
  "iamagayanjanitha@gmail.com",
  "thiliniwwijesiri@gmail.com",
  "ndgagani@gmail.com",
  "hdgagani@gmail.com",
  "sppd1328@gmail.com",
  "ranriv2014@gmail.com",
  "chathuripanditharathna@gmail.com",
  "adithyasadaru3@gmail.com",
  "nalinda_srinath@gmail.com",
  "pragnajaya@gmail.com",
  "lakmalininuligange@gmail.com",
  "rockhouse2002@gmail.com",
  "yapa1985@gmail.com",
  "rasi4galle@gmail.com",
  "manoripattithuwearachchi@gmail.com",
  "gkigayani5@gmail.com",
  "m.athukorala1985@gmail.com",
  "dileepgalle@gmail.com",
  "sudheera90@gmail.com",
  "amilaashan1@yahoo.com",
  "deepanivijethunga17@gmail.com",
  "hasanthaliyanarachchi5@gmail.com",
  "nihalkankanamge@gmail.com",
  "thathsaraniganegoda@gmail.com",
  "dineshadk915@gmail.com",
  "uduwalladuragesamanthika@gmail.com",
  "anaruwan4@gmail.com",
  "sanojaph@gmail.com",
  "chamikapasandani@gmail.com",
  "ilhama.imthi@gmail.com",
  "manoshika85@gmail.com",
  "sarassonali@yahoo.com",
  "tharangaprasadh4@gmail.com",
  "dilanthasumathipala@gmail.com",
  "vchathura@gmail.com",
  "upani.darshika@gmail.com",
  "withanagekumara29@gmail.com",
  "gihanchaminda@gmail.com",
  "indulakmali3@gmail.com",
  "jeyathikagunawardhana@gmail.com",
  "chandunu.jayasundara@gmail.com",
  "nilinidimantha@gmail.com",
  "dilusharavihari@gmail.com",
  "dilrukshithamodini@gmail.com",
  "chinthalma@gmail.com",
  "sujewah08@gmail.com",
  "jayamanna21k@gmail.com",
  "chamalki86@gmail.com",
  "dinushamunaweera6@gmail.com",
  "dinesh.tharanga9807@gmail.com",
  "arunasandira90@gmail.com",
  "shalikagamage20@gmail.com",
  "prolineadvertising@gmail.com",
  "yohan.godage@gmail.com",
  "maharafof89@gmail.com",
  "randhikahettiarachchi@gmail.com",
  "madavimcg@gmail.com",
  "priyanthigr@gmail.com",
  "cchathu100@gmail.com",
  "hansaniedu1@gmail.com",
  "gnwarusha@gmail.com",
  "nadee.krishanthi85@gmail.com",
  "harshanap123@gmail.com",
  "basheerfalulur@gmail.com",
  "shiraniayanthika76@gmail.com",
  "danuka.dulshan84@gmail.com",
  "ureshnadeen@gmail.com",
  "nadeekariyawasam@yahoo.com",
  "riyadsameera@gmail.com",
  "rhgchandi@gmail.com",
  "supersale46@gmail.com",
  "kulsichanaka@gmail.com",
  "chandikarcg@gmail.com",
  "chamadigajanayake@gmail.com",
  "mohan.chathuranga88@gmail.com",
  "iroshprasanjith@gmail.com",
  "manjulakumara88@gmail.com",
  "kaushi.emlk@gmail.com",
  "yamunarasangika6@gmail.com",
  "sakunalg@gmail.com",
  "ravindarangodage@gmail.com",
  "sudeshattanayaka@gmail.com",
  "harsharugby@gmail.com",
  "nisansalajagoda@gmail.com",
  "thilankaruwa@gmail.com",
  "ngmmanohara@gmail.com",
  "deshadpmn@gmail.com",
  "rackithag@gmail.com",
  "sanjayapradeep245@gmail.com",
  "pathumananda6@gmail.com",
  "amila22chathuranga@gmail.com",
  "randika8509@gmail.com",
  "lgmlgurug@gmail.com",
  "indigalle75@gmail.com",
  "tharaka1974@gmail.com",
  "raneshkalansooriya@gmail.com",
  "yamunasedarage@gmail.com",
  "sathsaranihimaya59@gmail.com",
  "wgtkmunasinghe@gmail.com",
  "anura.rcb@gmail.com",
  "prasadinigallage99@gmail.com",
  "tharangamanoj8806@gmail.com",
  "p.manupul@gmail.com",
  "grsprathibha@gmail.com",
  "jayanishamika89@gmail.com",
  "jayamannaauk@gmail.com",
  "chathurangaponnamperuma8@gmail.com",
  "me1983srk@gmail.com",
  "manoripriyadarshani373@gmail.com",
  "ushanmadushanka5@gmail.com",
  "jagathneel1973@gmail.com",
  "pathminishanika7@gmail.com",
  "medhagunawardhana@gmail.com",
  "menukalasanthi05@gmail.com",
  "thisarasjz@gmail.com",
  "wwisarasi.dmt@gmail.com",
  "rfirst77@gmail.com",
  "sashinipunchihewa@gmail.com",
  "chathustar@gmail.com",
  "akithsandew33846@gmail.com",
  "cha85janak@gmail.com",
  "dinushawijenayaka278@gmail.com",
  "sooriyarachchihimali@gmail.com",
  "jayonkadp@gmail.com",
  "sunathilakarukmali@gmail.com",
  "milamanisha@gmail.com",
  "nilanthizoysa@gmail.com",
  "prageethwishwajith@gmail.com",
  "nethminnethsara@gmail.com",
  "kpriyanga@gmail.com",
  "chenuthichenaya@gmail.com",
  "mwijeyananda@gmail.com",
  "sanojnayomi042@gmail.com",
  "elgurusinghe2000@gmail.com",
  "dilhaniprasanka2017@gmail.com",
  "gayaindin@gmail.com",
  "evildev360@gmail.com",
  "hirushalochana@gmail.com"
  
]);

export async function POST(req) {
  try {
    const { email } = await req.json();

    if (!email) {
      return NextResponse.json(
        { message: "Email is required" },
        { status: 400 }
      );
    }

    const normalizedEmail = email.toLowerCase().trim();

    if (!ALLOWED_EMAILS.has(normalizedEmail)) {
      return NextResponse.json(
        { message: "Access denied" },
        { status: 401 }
      );
    }

    return NextResponse.json(
      { message: "Access granted" },
      { status: 200 }
    );
  } catch (error) {
    return NextResponse.json(
      { message: "Invalid request" },
      { status: 500 }
    );
  }
}
